# Generated by Django 5.2.1 on 2025-05-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='video',
            name='analysis_metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Métadonnées d'analyse IA"),
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, help_text='Catégorie principale', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='corrected_text',
            field=models.TextField(blank=True, help_text='Texte corrigé par IA'),
        ),
        migrations.AddField(
            model_name='video',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='Mots-clés extraits et analysés'),
        ),
        migrations.AddField(
            model_name='video',
            name='subcategory',
            field=models.CharField(blank=True, help_text='Sous-catégorie', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='extracted_text',
            field=models.TextField(blank=True, default='', help_text='Texte extrait automatiquement par OCR'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['category'], name='uploader_vi_categor_6cd7ed_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['subcategory'], name='uploader_vi_subcate_1f44bc_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-uploaded_at'], name='uploader_vi_uploade_1b4174_idx'),
        ),
    ]
