# Generated by Django 5.2.1 on 2025-05-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_alter_video_options_video_analysis_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_transcription',
            field=models.TextField(blank=True, help_text="Transcription automatique de l'audio parlé"),
        ),
    ]
