# Generated by Django 5.2.1 on 2025-05-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_video_audio_transcription'),
    ]

    operations = [
        # Première étape : mettre à jour les valeurs NULL existantes à chaîne vide
        migrations.RunSQL(
            "UPDATE uploader_video SET audio_transcription = '' WHERE audio_transcription IS NULL;",
            reverse_sql="UPDATE uploader_video SET audio_transcription = NULL WHERE audio_transcription = '';",
        ),
        # Deuxième étape : modifier le champ pour avoir une valeur par défaut
        migrations.AlterField(
            model_name='video',
            name='audio_transcription',
            field=models.TextField(blank=True, default='', help_text="Transcription automatique de l'audio parlé"),
        ),
    ]
