# Generated by Django 5.2.1 on 2025-05-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20250529_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='corrected_audio_transcription',
            field=models.TextField(blank=True, default='', help_text='Transcription audio corrigée par IA'),
        ),
        migrations.AlterField(
            model_name='video',
            name='corrected_text',
            field=models.TextField(blank=True, help_text='Texte OCR corrigé par IA'),
        ),
    ]
