# Generated by Django 5.2.1 on 2025-05-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_video_corrected_audio_transcription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='has_speech',
            field=models.BooleanField(default=True, help_text='Indique si la vidéo contient de la parole détectée'),
        ),
        migrations.AddField(
            model_name='video',
            name='speech_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Métadonnées de détection vocale'),
        ),
    ]
